"""empty message

Revision ID: b9bba285a9e7
Revises: 2ac547b86560
Create Date: 2019-02-05 23:13:11.763564

"""

# revision identifiers, used by Alembic.
revision = 'b9bba285a9e7'
down_revision = '2ac547b86560'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('preferred_clinician', sa.String(length=128), nullable=False),
    sa.Column('appointment_reason', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###
