"""empty message

Revision ID: f153f1b5eea1
Revises: b9bba285a9e7
Create Date: 2019-02-06 00:25:19.468871

"""

# revision identifiers, used by Alembic.
revision = 'f153f1b5eea1'
down_revision = 'b9bba285a9e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'request_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'request_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
